"""schema initial : utilisateurs, clients, lots, supports, audit

Revision ID: 0c8c379d088a
Revises: 
Create Date: 2026-07-12 17:41:41.799226

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0c8c379d088a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifiant', sa.Text(), nullable=False),
    sa.Column('nom_complet', sa.Text(), nullable=False),
    sa.Column('mot_de_passe', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('actif', sa.Integer(), server_default='1', nullable=False),
    sa.Column('cree_le', sa.Text(), nullable=False),
    sa.Column('derniere_conn', sa.Text(), nullable=True),
    sa.CheckConstraint("role IN ('TECHNICIEN','RESPONSABLE','ADMINISTRATEUR')", name='ck_utilisateurs_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('horodatage', sa.Text(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entite', sa.Text(), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('hash_precedent', sa.Text(), nullable=False),
    sa.Column('hash_courant', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entite', 'audit', ['entite', 'entite_id'], unique=False)
    op.create_index('idx_audit_horodatage', 'audit', ['horodatage'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_client', sa.Text(), nullable=False),
    sa.Column('raison_sociale', sa.Text(), nullable=False),
    sa.Column('siret', sa.Text(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('code_postal', sa.Text(), nullable=True),
    sa.Column('ville', sa.Text(), nullable=True),
    sa.Column('contact_nom', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_telephone', sa.Text(), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.Text(), nullable=False),
    sa.Column('cree_par', sa.Integer(), nullable=False),
    sa.Column('archive', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('archive IN (0,1)', name='ck_clients_archive'),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_client')
    )
    op.create_index('idx_clients_raison', 'clients', ['raison_sociale'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_lot', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_reception', sa.Text(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Text(), server_default='OUVERT', nullable=False),
    sa.Column('nb_supports_annonce', sa.Integer(), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.Text(), nullable=False),
    sa.Column('cloture_le', sa.Text(), nullable=True),
    sa.CheckConstraint("statut IN ('OUVERT','EN_COURS','TERMINE','CLOTURE')", name='ck_lots_statut'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technicien_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_lot')
    )
    op.create_index('idx_lots_client', 'lots', ['client_id'], unique=False)
    op.create_index('idx_lots_statut', 'lots', ['statut'], unique=False)
    op.create_table('supports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('code_interne', sa.Text(), nullable=False),
    sa.Column('numero_serie', sa.Text(), nullable=True),
    sa.Column('modele', sa.Text(), nullable=True),
    sa.Column('constructeur', sa.Text(), nullable=True),
    sa.Column('capacite_octets', sa.Integer(), nullable=True),
    sa.Column('technologie', sa.Text(), nullable=True),
    sa.Column('interface', sa.Text(), nullable=True),
    sa.Column('smart_json', sa.Text(), nullable=True),
    sa.Column('sante', sa.Text(), nullable=True),
    sa.Column('hpa_detecte', sa.Integer(), server_default='0', nullable=True),
    sa.Column('dco_detecte', sa.Integer(), server_default='0', nullable=True),
    sa.Column('statut', sa.Text(), server_default='EN_ATTENTE', nullable=False),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.Text(), nullable=False),
    sa.CheckConstraint("destination IN ('REEMPLOI','DESTRUCTION','VALORISATION')", name='ck_supports_destination'),
    sa.CheckConstraint("sante IN ('OK','DEGRADE','DEFAILLANT','INCONNU')", name='ck_supports_sante'),
    sa.CheckConstraint("statut IN ('EN_ATTENTE','EN_COURS','EFFACE_VERIFIE','EFFACE_NON_VERIFIE','ECHEC','NON_EFFACABLE','DETRUIT_PHYSIQUEMENT')", name='ck_supports_statut'),
    sa.CheckConstraint("technologie IN ('HDD_SATA','SSD_SATA','SSD_NVME','SAS','USB','SD','SED','INCONNU')", name='ck_supports_technologie'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_interne')
    )
    op.create_index('idx_supports_lot', 'supports', ['lot_id'], unique=False)
    op.create_index('idx_supports_serie', 'supports', ['numero_serie'], unique=False)
    op.create_index('idx_supports_statut', 'supports', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_supports_statut', table_name='supports')
    op.drop_index('idx_supports_serie', table_name='supports')
    op.drop_index('idx_supports_lot', table_name='supports')
    op.drop_table('supports')
    op.drop_index('idx_lots_statut', table_name='lots')
    op.drop_index('idx_lots_client', table_name='lots')
    op.drop_table('lots')
    op.drop_index('idx_clients_raison', table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_audit_horodatage', table_name='audit')
    op.drop_index('idx_audit_entite', table_name='audit')
    op.drop_table('audit')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
