"""table certificats

Revision ID: 2604c0418c8b
Revises: 43162d818de0
Create Date: 2026-07-12 21:11:46.694134

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2604c0418c8b'
down_revision = '43162d818de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_cert', sa.Text(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('genere_le', sa.Text(), nullable=False),
    sa.Column('genere_par', sa.Integer(), nullable=False),
    sa.Column('contenu_sha256', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('cle_publique_id', sa.Text(), nullable=False),
    sa.Column('chemin_pdf', sa.Text(), nullable=False),
    sa.Column('token_verif', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['genere_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cert'),
    sa.UniqueConstraint('operation_id'),
    sa.UniqueConstraint('token_verif')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificats')
    # ### end Alembic commands ###
