"""table operations

Revision ID: 43162d818de0
Revises: 0c8c379d088a
Create Date: 2026-07-12 17:53:14.367167

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '43162d818de0'
down_revision = '0c8c379d088a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('support_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Text(), nullable=True),
    sa.Column('methode', sa.Text(), nullable=False),
    sa.Column('norme_reference', sa.Text(), server_default='NIST SP 800-88 Rev.1', nullable=False),
    sa.Column('nb_passes', sa.Integer(), nullable=True),
    sa.Column('debut', sa.Text(), nullable=False),
    sa.Column('fin', sa.Text(), nullable=True),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('resultat', sa.Text(), nullable=False),
    sa.Column('verification_faite', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verification_ok', sa.Integer(), nullable=True),
    sa.Column('verification_detail', sa.Text(), nullable=True),
    sa.Column('log_brut', sa.Text(), nullable=True),
    sa.Column('log_sha256', sa.Text(), nullable=False),
    sa.Column('outil_version', sa.Text(), nullable=True),
    sa.Column('importe_le', sa.Text(), nullable=False),
    sa.CheckConstraint("resultat IN ('SUCCES','ECHEC','INTERROMPU')", name='ck_operations_resultat'),
    sa.ForeignKeyConstraint(['support_id'], ['supports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technicien_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operations_debut', 'operations', ['debut'], unique=False)
    op.create_index('idx_operations_support', 'operations', ['support_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_operations_support', table_name='operations')
    op.drop_index('idx_operations_debut', table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
